micronaut:
  application:
    name: veiculoService
datasources:
  default:
    url: jdbc:postgresql://127.0.0.1:5432/dbveiculo
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '123456'
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      packages: 'com.model'
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true